### ISSUE TITLE
Mention Adruino alternative in the Readme

### ISSUE THREAD

**Issue by Loriowar** [tjob/ft-vac-control#1]
Hi! Thanks for your project. It helps me to build my own implementation of [Festool receiver handler](https://github.com/Loriowar/festool_ct-f_im_handler). It's built on Arduino Nano and for some people might be even simpler in the implementation in compare with Pico. If you decide this is worth you can add the mention of the [Arduino alternative](https://github.com/Loriowar/festool_ct-f_im_handler) in the Readme.

**Comment by tjob** [comment]
Glad you found this helpful,  I added a link to your repo.
